# Generated by Django 2.1 on 2019-09-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='Job Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='exp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='req_skills',
            field=models.TextField(max_length=50, verbose_name='Required Skills'),
        ),
    ]
