# Generated by Django 2.1 on 2019-09-19 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190918_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobs',
            name='type',
            field=models.CharField(default='Full time', max_length=20, verbose_name='Job type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='exp',
            field=models.PositiveIntegerField(verbose_name='Experience (in years)'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='req_skills',
            field=models.TextField(verbose_name='Required Skills'),
        ),
    ]
