# Generated by Django 2.1 on 2019-09-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_appliedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
    ]
