# Generated by Django 2.1 on 2019-09-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_skills',
            field=models.CharField(max_length=50, verbose_name='Primary Skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='s_skills',
            field=models.CharField(max_length=50, verbose_name='Secondary Skills'),
        ),
    ]
