# Generated by Django 2.1 on 2019-09-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190918_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp',
            field=models.PositiveIntegerField(default=2, verbose_name='Experience'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Profile pic'),
        ),
    ]
