# Generated by Django 2.1 on 2019-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190919_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exp',
            field=models.PositiveIntegerField(null=True, verbose_name='Experience'),
        ),
    ]
